RDMA/srpt: fix function pointer cast warnings
[ Upstream commit eb5c7465c3240151cd42a55c7ace9da0026308a1 ]

clang-16 notices that srpt_qp_event() gets called through an incompatible
pointer here:

drivers/infiniband/ulp/srpt/ib_srpt.c:1815:5: error: cast from 'void (*)(struct ib_event *, struct srpt_rdma_ch *)' to 'void (*)(struct ib_event *, void *)' converts to incompatible function type [-Werror,-Wcast-function-type-strict]
 1815 |                 = (void(*)(struct ib_event *, void*))srpt_qp_event;

Change srpt_qp_event() to use the correct prototype and adjust the
argument inside of it.

Fixes: a42d985bd5b2 ("ib_srpt: Initial SRP Target merge for v3.3-rc1")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20240213100728.458348-1-arnd@kernel.org
Reviewed-by: Bart Van Assche <bvanassche@acm.org>
Signed-off-by: Leon Romanovsky <leon@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>
(cherry picked from commit e333db03ab6ee3bd3596739724250a9a374dd466)
[vegard: fix trivial conflicts due to missing commit
 10eac19bb272415cad6f28ebe8c055b648f334b1 ("IB/srpt: Fix kernel-doc
 warnings in ib_srpt.c") and commit d4ee7f3a4445ec1b0b88af216f4032c4d30abf5a
 ("RDMA/srpt: Make debug output more detailed")]
Signed-off-by: Vegard Nossum <vegard.nossum@oracle.com>